- hosts: localhost
  tasks:
    - name: Run database container
      docker_container:
        name: 'db'
        image: 'mariadb'
        state: 'started'
        network_mode: "host"
        restart_policy: "always"
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: 'VerySecret!'

    - name: Run Wordpress container
      docker_container:
        name: 'wp'
        image: 'wordpress'
        state: 'started'
        network_mode: "host"
        restart_policy: "always"
        ports:
          - "80:80"
        env:
          WORDPRESS_DB_HOST: '127.0.0.1'
          WORDPRESS_DB_PASSWORD: 'VerySecret!'
